### ISSUE TITLE
yes, it's the shopping list issue

### ISSUE THREAD

**Issue by asayeed** [EllaVator/EllaVator#10]
@psibre and I spent a little more time afterwards attempting to shop for parts.  This is slightly harder than you might think, because we have some special accessory requirements.  We are going to order most of @bryandeng's suggestions, which are the basic items:

Raspberry Pi 2 Model B: 
http://de.rs-online.com/web/p/products/8326274/

Appropriate housing:
http://de.rs-online.com/web/p/products/8193646/

Power supply:
http://de.rs-online.com/web/p/products/8226373/

2 of these SD cards:
http://de.rs-online.com/web/p/products/7504795/

BUT, what we have left are the following:
* RS232 level shifter (because the GPIO port is not run at enough power to behave like an old-school serial port)
* Actual RS232 serial port (does the elevator require male or female? Need to check) 
  * We need to check whether or not we need a special case to accommodate the level shifter, etc, or an extension outside the case.  It would look kind of silly to have another board hanging out of the case, but we may have no other option.  This is *selbstgebastelt* electronics for you!
* USB audio with appropriate audio *input*.  The Adafruit website has a recommended audio card, but they seem to suggest that they haven't tested the input mic.  However, there is a page for this (http://elinux.org/RPi_VerifiedPeripherals#USB_Sound_Cards) -- we may need to order it separately, since the RS web site doesn't seem to have these, or at least we couldn't find them. 
* Cheap HDMI cable.  Does anyone know where to get it for cheaper?  Anyway 6EUR is not a terrible sacrifice. We might be able to get this from Systems Group, since we only need it temporarily for testing.

**Comment by asayeed** [comment]
The RS website doesn't seem to have USB audio devices, but Amazon.de has several costing from 5-20 EUR depending on brand. Anything using USB1.1 will work with the Pi and Linux. Need to find the width of the jack inside the elevator (3.5 or 2.5mm).  So two reasons for me to make a journey inside the elevator cabinet tomorrow.  We're getting there! :)

**Comment by psibre** [comment]
I'm not that big a fan, but we could of course just order all of it from Amazon, right?

**Comment by asayeed** [comment]
We could indeed -- unless someone has an alternative that *does* sell cheap USB audio.  The level shifter for the Raspberry Pi is also a bit tricky to get from RS, which surprises me.  It's name in German is, by the way "Pegelwandler".

**Comment by asayeed** [comment]
Two options also for the RS232 connection.  The cheap one is this:

http://www.amazon.de/SODIAL-MAX3232-Schnittstelle-TTL-Konverter-Modul-DB9-Anschluss/dp/B00K67XD7Y/ref=pd_sim_sbs_147_3?ie=UTF8&refRID=1E99KSW5Z4A0RB0VVXEJ

This one uses little jumper cables to connect from the GPIO.  The online tutorials for this kind of thing seem to suggest that most people use a bread board to hold all these things in place, but I don't think this is necessarily necessary.

The more expensive one, but possibly easier to handle is: 

http://www.amazon.de/LinkSprite-RS232-Shield-Raspberry-Pi/dp/B00KW4TODS/ref=sr_1_fkmr1_1?ie=UTF8&qid=1433862137&sr=8-1-fkmr1&keywords=rs232+pegelwandler+raspberry+pi

This one would also require a GPIO extension cable.  Tidier and more secure than using the jumper cables.  But it's "done for you", so to speak.

The bad thing is that there is no actual housing for either of these, so they would be dangling off the Pi.  Wrap them in electrical tape, maybe?

**Comment by asayeed** [comment]
OK, I checked the elevator cabinet physically.  It takes a 3.5mm jack (so most of the USB audio cards would work without an adapter).  The computer has a male serial port, whereas the RS232 level shifters are female, so we'd need a gender changer.  That pretty much completes the shopping list, once we decide on which cards to get. 

Unfortunately I forgot my laptop (I rarely bring it with me), but I do have my tablet with me, if anyone wants to complete the shopping with me today (during class?).

**Comment by asayeed** [comment]
I have placed the order, including a small wifi dongle, because it would be annoying to have to search for plugs everytime we decide we need e.g. a new java version or want to clone a git repo, etc, etc.  

Everything EXCEPT the serial port should be here next week.  We can briefly live without the serial port -- it will be here the week after as it is a specialty item.  

I am going to close this issue because the shopping list is over.  I will open an issue later for the installation and setup of the Pi, which should begin next week in class.
