### ISSUE TITLE
some assembly required

### ISSUE THREAD

**Issue by asayeed** [EllaVator/EllaVator#19]
Most of the parts have arrived, so it's time for the issue for setting up the Pi.  I will bring (note to self!!!) a tool set to Wednesday's class with the parts, and a spare monitor, mouse, and keyboard.  I will also load a Raspbian image onto one of the SD cards.  As I predicted, the serial port will probably come next week or later, but that's fine.  This issue is opened just to keep track of anything we discover we didn't realize...

**Comment by asayeed** [comment]
Of course, NOW I realize that our only way to test the physical connection via the serial port is via the elevator itself.  I am thinking that we need one more part, unless one of you has an old-style serial port on your machines...

**Comment by psibre** [comment]
I wonder if we could use a random old PC with a serial port to impersonate the elevator to the Pi?

**Comment by asayeed** [comment]
We could do this if someone around us has a random old PC -- for sure.  And a serial cable, but maybe Systems Group has some spare ones.  They've lent me a few things for temporary use so far.  Maybe they even have an old PC with a serial port, I'll ask.

**Comment by psibre** [comment]
Pending the serial port delivery, we should try and fire up the Pi today!

**Comment by asayeed** [comment]
Indeed we will be. I will be coming to class with an armful of stuff. Actually, we need a couple of MORE things, that being a speaker and a mic, but I assumed that you would be actually likely to have these. :)

**Comment by asayeed** [comment]
The gender changer and the "actual" wifi dongle arrived, but no serial port!

**Comment by asayeed** [comment]
We have serial port, I repeat, we have serial port.
