### ISSUE TITLE
OpenDial prototype

### ISSUE THREAD

**Issue by psibre** [EllaVator/EllaVator#3]

**Comment by psibre** [comment]
Planned prototype workflow:
**User** "Hi Ella!"
**Ella** "Hi User!"
**User** "Two please."
**Ella** "You said 'two'."
*Ella pushes button 2*

* [ ] Text first, using the OpenDial framework.
* [ ] Add TTS output (MaryTTS).
* [ ] Try to integrate speech recognition (Sphinx4).

**Comment by psibre** [comment]
Please use the [`opendial`](/EllaVator/EllaVator/tree/opendial) branch.

**Comment by HoffmannAJ** [comment]
@HoffmannAJ (I'd like to try OpenDial for a prototype)

**Comment by bryandeng** [comment]
I'm also going for this.

**Comment by benti** [comment]
I'll join this group.

**Comment by benti** [comment]
As Kata already proposed in the other group it would probably be nice to meet tomorrow. I'll be there.

**Comment by HoffmannAJ** [comment]
I'll also be there. :)

**Comment by bryandeng** [comment]
Also coming.

**Comment by bryandeng** [comment]
Hi all:

As the release manager of this team, I now give some instructions on collaboration.

All the work on OpenDial demo will be aggregated at `bryandeng:opendial`. I'm responsible for code review and merge within this team. In the end I'll organize the commits and send a PR to `EllaVator:opendial` to make our work merged into the organization repo.

If you want to join this team, please do the following:

`git remote add team https://github.com/bryandeng/EllaVator.git`

and sync changes from `bryandeng:opendial` to your own `opendial` branch frequently.

When you want to contribute code to `bryandeng:opendial`, do the changes in a new branch `my-shiny-feature`, push to GitHub, then make a PR from `you:my-shiny-feature` to `bryandeng:opendial`.

After your contribution is merged, please click to delete your `my-shiny-feature` branch on GitHub. Then locally sync changes from `bryandeng:opendial` to your `opendial` branch by doing

`git fetch team`
`git checkout opendial`
`git merge team/opendial`
`git branch -d my-shiny-feature`

Please don't touch the `master` branch.

**Comment by HoffmannAJ** [comment]
Hi!
I just wanted to submit my opendomain-file for the opendial prototype.
But it seems to me all I have done was creating a big mess.
I've never worked with different branches and it looks to me that I somehow somewhere did something wrong and trying to fix it only seemed to make it worse.

The domain-file i've wirtten inlcudes the nlg, nlu as well as the dm and covers the basic functions for the prototype.
But I guess I might need some help with git.

**Comment by HoffmannAJ** [comment]
Hi all!

Has anyone tried to add TTS or integrate speech Recognition with opendial?

I tried to do both but I can't figure out how to do it.
Adding TTS seems to work I do get the output [Module MaryTTS successfully attached]. But there is no speech Output during the systems turn and I can't find a button to enable that.

If I try using Sphinx for speech recognition I get error messages stating that the location of my grammar is wrong. (I doesn't seem to make a difference whether I attach them in the domain-file or in the command line.)

From what I understand the system is already in the same folder as the domain file is. To make things easy I simply copied the grammar to that folder. (Of course I also tried to put it in different folders.)
So the path should be merely the files name. I'm not quite sure whether the filename extension should be included.

If I do include it the error message:
[cannot attach SphinxASR: Property exception component:'jsgfGrammar' property:'grammarLocation' - Bad URL C:\opendial-version1.3b\opendial-version1.3b\domains/unknown protocol: c edu.cmu.sphinx.util.props.InternalConfigurationException: Bad URL C:\opendial-version1.3b\opendial-version1.3b\domains/unknown protocol: c]
appears.

If I don't include the filename extension the message:
[cannot attach SphinxASR: java.lang.RuntimeException: Grammar file C:\opendial-version1.3b\opendial-version1.3b\domains\demo cannot be found]
is given.

The file I used to create those errors was the "demo.gram" file that is included in the folder of the sphinx plugin.

**Comment by benti** [comment]
For MaryTTS, I have something that works quite well, though it is maybe not perfectly integrated into the opendial api: https://github.com/benti/EllaVator/blob/mary-tts/src/main/java/MaryTTS.java

The Module file from the opendial website does not seem to work. I couldn't really figure out why, so I modified it.

I also tried Sphinx, but that does not work well enogh yet.

**Comment by psibre** [comment]
@HoffmannAJ The error message
```
[cannot attach SphinxASR: Property exception component:'jsgfGrammar' property:'grammarLocation' - 
Bad URL C:\opendial-version1.3b\opendial-version1.3b\domains/unknown protocol: c 
edu.cmu.sphinx.util.props.InternalConfigurationException: Bad URL C:\opendial-version1.3b\opendial-version1.3b\domains/unknown protocol: c]
```
indicates what is wrong: you're passing in a raw Windows path, which results in a malformed URL.

**Comment by HoffmannAJ** [comment]
@ psibre  
Thank you for your answer.
I have tried some more things but I still couldn't load the grammar.

@  benti 
It's great to hear that you found the problem with the Mary module and where able to fix it!
As I have right now run out of ideas how to get sphinx working, I'm excited to see tomorrow how it is done!

**Comment by bryandeng** [comment]
Dear teammates:

We now include OpenDIal as a git submodule, please do
`git submodule update --init --recursive`
before building since gradle won't automatically download OpenDIal for you.

**Comment by psibre** [comment]
Actually, this is done, but not finished. Closing this issue.
