### ISSUE TITLE
Project report

### ISSUE THREAD

**Issue by benti** [EllaVator/EllaVator#59]
Hi everybody,

Let's try authorea for our project report:
https://www.authorea.com/users/50452/articles/58685/_show_article

I created this document and invited everybody I could get email addresses from. I will add everybody who sends me their email address.

The structure in the document is just a proposal. If you have better ideas go ahead and change everything or discuss it in the comments section...

**Comment by LauraRF** [comment]
I'll start writing a small chapter or subchapter on the jsgf grammar.

**Comment by naszka** [comment]
Hey, I added an outline for the report, feel free to edit /choose a section
[on my fork](https://github.com/naszka/report)
@benti : I just realized you already wrote one, but it is virtually the same.

**Comment by LauraRF** [comment]
I wanted to upload the photo I've taken of the setup for the reverberaton recordings, so that it can be used in the report. Is there already a place / folder on EllaVator where everything for the report has to go?

**Comment by benti** [comment]
I'll start writing about travis now.

**Comment by LauraRF** [comment]
I will upload a file (project_report.tex) that subsumes all of our individual latex files / chapters, so that we only have to compile the project_report.tex file. I'm working on it now, but I'm having some problems pushing it into EllaVator Report. I'll hopefully have that fixed until tomorrow.

**Comment by psibre** [comment]
Please continue discussion in the [report](/Ellavator/report) repo. :grinning:
