### ISSUE TITLE
Virtualize raspberry pi 2

### ISSUE THREAD

**Issue by psibre** [EllaVator/EllaVator#7]
Use [qemu](http://www.qemu.org/)...

**Comment by bryandeng** [comment]
I'm in.

**Comment by bryandeng** [comment]
I find that all the posts about such virtualization require a qemu-kernel from
http://xecdesign.com/downloads/linux-qemu/kernel-qemu

But now the page is 404.

**Comment by psibre** [comment]
http://web.archive.org/web/20150214035104/http://www.xecdesign.com/downloads/linux-qemu/kernel-qemu

**Comment by bryandeng** [comment]
It works! I'll open a wiki page for this.

**Comment by psibre** [comment]
@bryandeng Tried the PDF linked in the wiki using something like:
```
$ qemu-system-arm -kernel kernel-qemu -cpu arm1176 -m 256 -M versatilepb -append "root=/dev/sda2 panic=1 init=/bin/sh rw" -hda 2015-05-05-raspbian-wheezy.img 
WARNING: Image format was not specified for '2015-05-05-raspbian-wheezy.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
```
Any ideas?

**Comment by bryandeng** [comment]
I didn't see this when I ran the command. Which version of qemu are you using? Actually I skipped the image resizing operation.

**Comment by psibre** [comment]
I think we should try to include another subproject to act as a virtual pi. Something along the lines of
```
$ ./gradlew :pivm:run
[...]
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:createRasPiSdCardImage
:pivm:run
```
where the `run` task in the `pivm` subproject would run some startup script that fires up a RasPi VM which boots our SD card image and starts the EllaVator app or runs through an integration test suite.

We'll discuss this and other things tomorrow.

**Comment by bryandeng** [comment]
Some tips:
http://www.tomaz.me/2013/12/02/running-travis-ci-tests-on-arm.html

**Comment by psibre** [comment]
@bryandeng awesome for the Travis integration! Not sure whether we can manage that -- I think our tests may end up running too long. Travis integration is definitely a desirable, but the qemu-based virtual pi stuff will probably have to be run as a non-continuous integration test, i.e., on demand, on a local machine.

**Comment by bryandeng** [comment]
@psibre Yes, we can use Travis to do some generic Java testing. And they have nice caching mechanism to shorten the time for running tests.

**Comment by bryandeng** [comment]
@psibre What are the next steps?

**Comment by psibre** [comment]
We just provisioned project file space on coli at `/proj/courses/elevator15`.
@asayeed will put the SD card image there.
