### ISSUE TITLE
Finishing up the report

### ISSUE THREAD

**Issue by tastyminerals** [EllaVator/EllaVator#86]
Hi guys. We decided to review the status of our report and see what else can be added to the table.
Below is a list of items that everyone is invited to contribute.

**Testing** -- Alex takes this.
**Raspberri Pi** (replace pi4j section), **Serial cable connection setup** (some undocumented stuff), **Development tools** (some info about serial port tools) - Pavel  takes this.

**ASR** (Arif's presentation) -- ???
**Acoustic model** (ask grandmaster Ingmar)  -- ???
**Language model** -- ???
**TTS** (add some general info) -- ???

Make your pick!

**Comment by HoffmannAJ** [comment]
Hey 
I guess I might be able to write a small article about the structure and components of TTS Mary.

**Comment by tastyminerals** [comment]
Nice!

**Comment by HoffmannAJ** [comment]
Happy New Year!
 
 I just had a look at the open Tickets in EllaVator.
 With the deadline of our project now fast approaching, may I assume, 
 that there won't be any work put on for example Ticket #80 and #79?
  
 I'm thinking about writing a small chapter to extend the open dial section.
 I guess I could mention my thoughts about the problems described in #79.

**Comment by sirifarif** [comment]
You mean to extend the report?

**Comment by HoffmannAJ** [comment]
A little, yes.
It might be just half a page or a page.
I thought we could include the general idea how our dialogue should turn out as have already described in ticket #6.
Do you think that is a good idea?

**Comment by sirifarif** [comment]
Yes, I think its good. 
Just include in in a separate tex file in the main file.

**Comment by HoffmannAJ** [comment]
I have just created a pull request. I named the new chapter "General thoughts", as I couldn't come up with a better name. ^^" Maybe some one else has a better idea!
The chapter does include some of the ideas mentioned in ticket #79 it does not yet contain anything from ticket #80. 
@naszka , @LauraRF  the two of you worked on that, right? Does one of you fee like writing about this issue?
