### ISSUE TITLE
no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver

### ISSUE THREAD

**Issue by sirifarif** [EllaVator/EllaVator#89]
I got the following error while doing a fresh run and following the steps as in *README* file.

I guess it doesn't find the serial port. Any idea?

```
 $ ./gradlew :run
:opendial:compileJava UP-TO-DATE
:opendial:compileGroovy UP-TO-DATE
:opendial:processResources UP-TO-DATE
:opendial:classes UP-TO-DATE
:opendial:jar
:sphinx4:sphinx4-data:compileJava UP-TO-DATE
:sphinx4:sphinx4-data:compileGroovy UP-TO-DATE
:sphinx4:sphinx4-data:processResources UP-TO-DATE
:sphinx4:sphinx4-data:classes UP-TO-DATE
:sphinx4:sphinx4-data:jar UP-TO-DATE
:sphinx4:sphinx4-core:compileJava UP-TO-DATE
:sphinx4:sphinx4-core:compileGroovy UP-TO-DATE
:sphinx4:sphinx4-core:processResources UP-TO-DATE
:sphinx4:sphinx4-core:classes UP-TO-DATE
:sphinx4:sphinx4-core:jar UP-TO-DATE
:compileJava
Note: /Users/arif/workspace/elevator2015/test/EllaVator/src/main/java/SerialPortController.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileGroovy UP-TO-DATE
:processResources UP-TO-DATE
:classes
:copySettingsXml UP-TO-DATE
:run
java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
Exception in thread "main" java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1865)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:83)
	at SerialPortController.<init>(SerialPortController.java:33)
	at ElevatorController.<init>(ElevatorController.java:11)
	at ModuleElla.<clinit>(ModuleElla.java:33)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at opendial.Settings.fillSettings(Settings.java:243)
	at opendial.readers.XMLDomainReader.extractPartialDomain(XMLDomainReader.java:147)
	at opendial.readers.XMLDomainReader.extractDomain(XMLDomainReader.java:109)
	at opendial.readers.XMLDomainReader.extractDomain(XMLDomainReader.java:64)
	at OpenDialDemo.main(OpenDialDemo.java:14)
> Building 95% > :run
```

**Comment by asayeed** [comment]
I think this has to do with RXTX libraries needing to be in the right place, and that has to be done separately for each system.  At least as I understand it from @tastyminerals .  Any way we could bypass this?  I'm not familiar with the nitty-gritty of this part, nor do I understand enough about gradle to bypass it myself.

**Comment by tastyminerals** [comment]
If you are using Ubuntu, first install **librxtx-java**. Then you need to copy `Rxtx.jar` and .so files into java dirs.
Here are a few websites that explain what needs to be done.
[first link](http://java-buddy.blogspot.com.by/2013/06/setup-rxtx-jar-and-so-for-ubuntu.html)
[second link](http://www.jcontrol.org/download/readme_rxtx_en.html)

**Comment by sirifarif** [comment]
After copying the files 
```
RXTXcomm.jar
librxtxSerial.jnilib
```
i got the exception
 ```NoSuchPortExcetion: gnu.io.NoSuchPortException```.

Is it that I dont have a port or the installation was not good?

**Comment by tastyminerals** [comment]
if you don't have a serial port (working `/dev/ttyS0`) on your system you won't be able to start the project.

**Comment by asayeed** [comment]
Yes, I suggest commenting out the bit of the code that requires actually
starting the serial port access just for the purpose of debugging the
single problem that Pavel identified in loading some of the dialogue
management stuff, as I understand it.

Yours,
--Asad.

**Comment by sirifarif** [comment]
OK, @tastyminerals could you suggest on how to reproduce the *original* error i.e #88. I mean which code to comment etc.

**Comment by asayeed** [comment]
Yeah, @tastyminerals, could you just create a branch without the serial
port stuff or something?  Then we can merge @sirifarif's changes back
into the main branch when he's fixed whatever gradle/OpenDial/whatever
problem there is.

Yours,
--Asad.

**Comment by tastyminerals** [comment]
Try commenting out line **33** and line **125** in `ModuleElla.java` file.
As for a separate build without serial resources, I wish I knew how to exclude this in gradle.

**Comment by sirifarif** [comment]
After commenting the line *33* and *125*, I have successfully run the project. :)
